# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkShow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='super',
            field=models.BooleanField(default=False),
        ),
    ]
