# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talkShow', '0002_user_super'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='talk_show_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talkShow.TalkShow'),
        ),
    ]
