# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talkShow', '0007_remove_subject_talk_show_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='talkShow.User'),
        ),
    ]
