# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talkShow', '0008_auto_20171113_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='user_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='talkshowsubject',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='talkshowsubject',
            old_name='talk_show_id',
            new_name='talk_show',
        ),
        migrations.RenameField(
            model_name='talkshowsubject',
            old_name='user_id',
            new_name='user',
        ),
    ]
